# Generated by Django 5.2.3 on 2025-06-15 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecteddata',
            name='file_path',
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='forensic_data/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'csv'])]),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forensicsession',
            name='analysis_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='data_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('calls', 'Call Logs'), ('contacts', 'Contacts'), ('images', 'Images'), ('videos', 'Videos'), ('audio', 'Audio'), ('browser', 'Browser History'), ('whatsapp', 'WhatsApp Data'), ('location', 'Location Data')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_data', to='api.forensicsession'),
        ),
        migrations.AlterField(
            model_name='forensicsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('analyzed', 'Analyzed')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='forensicsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=100)),
                ('result_data', models.JSONField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_important', models.BooleanField(default=False)),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.collecteddata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='api.forensicsession')),
            ],
        ),
    ]
