# Generated by Django 5.2.3 on 2025-06-15 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_collecteddata_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Collected Data'},
        ),
        migrations.AlterModelOptions(
            name='forensicsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='collecteddata',
            name='analysis_result',
        ),
        migrations.RemoveField(
            model_name='forensicsession',
            name='analysis_report',
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='forensicsession',
            name='save_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='api.collecteddata'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='result_type',
            field=models.CharField(choices=[('suspicious', 'Suspicious'), ('normal', 'Normal'), ('important', 'Important')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='data_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('calls', 'Appels'), ('contacts', 'Contacts'), ('images', 'Images'), ('videos', 'Vidéos'), ('audio', 'Audio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_items', to='api.forensicsession'),
        ),
        migrations.AlterField(
            model_name='forensicsession',
            name='device_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='forensicsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=50),
        ),
    ]
