# Generated by Django 5.2.3 on 2025-06-15 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_analysisresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='forensicsession',
            name='save_path',
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='data_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('calls', 'Appels'), ('contacts', 'Contacts'), ('images', 'Images'), ('videos', 'Vidéos'), ('audio', 'Audio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='file',
            field=models.FileField(default='collected_data/default.json', upload_to='forensic_data/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='forensicsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
