# Generated by Django 5.2.3 on 2025-07-02 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_forensicsession_android_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donnée Collectée', 'verbose_name_plural': 'Données Collectées'},
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom original du fichier'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='data_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('calls', 'Appels'), ('contacts', 'Contacts'), ('images', 'Images'), ('videos', 'Vidéos'), ('audio', 'Audio'), ('device_report', 'Rapport Appareil'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='file',
            field=models.FileField(upload_to='forensic_data/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'csv', 'zip'])], verbose_name='Fichier de données'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Taille du fichier (octets)'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='is_analyzed',
            field=models.BooleanField(default=False, verbose_name='Analysé'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='item_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'éléments"),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AddIndex(
            model_name='collecteddata',
            index=models.Index(fields=['data_type'], name='api_collect_data_ty_86c01f_idx'),
        ),
        migrations.AddIndex(
            model_name='collecteddata',
            index=models.Index(fields=['is_analyzed'], name='api_collect_is_anal_3f4f02_idx'),
        ),
        migrations.AddIndex(
            model_name='collecteddata',
            index=models.Index(fields=['session'], name='api_collect_session_47accb_idx'),
        ),
    ]
