# Generated by Django 5.2.3 on 2025-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_collecteddata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicsession',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
