# Generated by Django 5.2.3 on 2025-06-29 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_forensicsession_android_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='forensic_reports/%Y/%m/%d/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_summary', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.forensicsession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('fraud', 'Fraude'), ('sentiment', 'Sentiment'), ('anomaly', 'Anomalie'), ('llm', 'Analyse LLM'), ('geo', 'Géolocalisation'), ('network', 'Réseau')], max_length=20)),
                ('result_json', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.collecteddata')),
            ],
            options={
                'ordering': ['-is_critical', '-confidence'],
                'indexes': [models.Index(fields=['analysis_type'], name='analysis_an_analysi_d1ccc8_idx'), models.Index(fields=['is_critical'], name='analysis_an_is_crit_0ba06e_idx')],
            },
        ),
    ]
