# Generated by Django 5.2.3 on 2025-07-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forensicreport',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Rapport Forensique', 'verbose_name_plural': 'Rapports Forensiques'},
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis_type',
            field=models.CharField(choices=[('fraud', 'Fraude'), ('sentiment', 'Sentiment'), ('anomaly', 'Anomalie'), ('llm', 'Analyse LLM'), ('network', 'Réseau'), ('geo', 'Géolocalisation')], max_length=20),
        ),
    ]
